/* Inserts comentarios
Informações fictícias geradas com IA */

INSERT INTO comentarios (post_id, autor_comentario, email_comentario, texto, data_comentario, aprovado) VALUES
(111, 'Beatriz Nunes', 'beatriz.n@exemplo.com', 'Conteúdo muito bem explicado, obrigado por compartilhar!', '2025-09-01 10:15:23', 1),
(145, 'Ricardo Almeida', 'ricardo.a@exemplo.com', 'Excelente ponto de vista. Não havia pensado nisso.', '2025-09-01 11:45:10', 1),
(102, 'Camila Santos', 'camila.s@exemplo.com', 'Este guia é exatamente o que eu precisava. Parabéns!', '2025-09-01 14:22:05', 1),
(122, 'Fernando Costa', 'fernando.c@exemplo.com', 'Dicas muito úteis sobre segurança, vou aplicar todas.', '2025-09-01 16:50:30', 0),
(133, 'Letícia Oliveira', 'leticia.o@exemplo.com', 'Ótimo artigo! Ajudou muito na estratégia do meu blog.', '2025-09-01 18:05:00', 1),
(108, 'Gustavo Pereira', 'gustavo.p@exemplo.com', 'Como designer, achei a análise muito pertinente. Fantástico!', '2025-09-02 09:12:45', 1),
(149, 'Mariana Ferreira', 'mariana.f@exemplo.com', 'Um tema muito necessário de ser discutido. Obrigado!', '2025-09-02 10:30:18', 1),
(117, 'Tiago Martins', 'tiago.m@exemplo.com', 'MongoDB é uma ótima escolha para APIs RESTful. Concordo plenamente.', '2025-09-02 11:25:55', 0),
(139, 'Sofia Ribeiro', 'sofia.r@exemplo.com', 'Adorei as receitas! Parecem fáceis e deliciosas.', '2025-09-02 13:14:21', 1),
(125, 'Rafael Souza', 'rafael.s@exemplo.com', 'A crítica musical foi perfeita. Capturou a essência do álbum.', '2025-09-02 15:55:43', 1),
(101, 'Vanessa Lima', 'vanessa.l@exemplo.com', 'Marketing digital está sempre mudando, bom ficar por dentro.', '2025-09-02 17:33:12', 1),
(142, 'José Silva', 'jose.s@exemplo.com', 'Muito informativo, obrigado!', '2025-09-02 19:40:00', 0),
(110, 'Alice Gomes', 'alice.g@exemplo.com', 'A literatura de ficção científica é fascinante. Ótimo post!', '2025-09-03 08:20:11', 1),
(128, 'Bruno Azevedo', 'bruno.a@exemplo.com', 'As dicas para entrevista online foram muito valiosas. Usei e consegui o emprego!', '2025-09-03 09:00:37', 1),
(136, 'Clara Dias', 'clara.d@exemplo.com', 'A série é boa, mas discordo de alguns pontos da sua análise.', '2025-09-03 10:11:02', 1),
(104, 'Daniel Rocha', 'daniel.r@exemplo.com', 'Amo fotografia! Vou testar essas dicas na minha próxima viagem.', '2025-09-03 11:23:45', 1),
(148, 'Helena Barbosa', 'helena.b@exemplo.com', 'Finalmente um artigo que desmistifica os alimentos orgânicos.', '2025-09-03 12:00:00', 0),
(120, 'Fábio Castro', 'fabio.c@exemplo.com', 'O conceito de MVP é crucial para qualquer startup. Excelente explicação.', '2025-09-03 13:45:19', 1),
(114, 'Isabela Neves', 'isabela.n@exemplo.com', 'Que resumo incrível da história da computação!', '2025-09-03 14:30:50', 1),
(131, 'Jorge Medeiros', 'jorge.m@exemplo.com', 'Comunicação não-violenta deveria ser ensinada nas escolas.', '2025-09-03 15:22:33', 1),
(106, 'Laura Melo', 'laura.m@exemplo.com', 'Organização financeira é tudo. Este passo a passo é perfeito.', '2025-09-03 16:18:09', 1),
(119, 'Marcos Vinícius', 'marcos.v@exemplo.com', 'Sustentabilidade é o futuro. Muito bom ver isso aplicado ao design.', '2025-09-03 17:05:21', 0),
(135, 'Natália Costa', 'natalia.c@exemplo.com', 'Não vejo a hora de jogar esses lançamentos!', '2025-09-03 18:40:00', 1),
(103, 'Otávio Ramos', 'otavio.r@exemplo.com', 'Fiz o risoto e ficou divino! Receita aprovada.', '2025-09-04 09:30:15', 1),
(123, 'Patrícia Barros', 'patricia.b@exemplo.com', 'Gadgets inovadores são minha paixão. Adorei a lista.', '2025-09-04 10:00:55', 1),
(141, 'Sérgio Tavares', 'sergio.t@exemplo.com', 'Trabalho remotamente há 5 anos e concordo com todos os desafios e vantagens.', '2025-09-04 10:45:00', 1),
(112, 'Tatiana Cunha', 'tatiana.c@exemplo.com', 'Psicologia das cores é um assunto muito interessante para marketing.', '2025-09-04 11:15:30', 1),
(129, 'Vitor Correia', 'vitor.c@exemplo.com', 'Figma realmente mudou o jogo para o design de interfaces.', '2025-09-04 12:00:00', 0),
(146, 'Yasmin Santos', 'yasmin.s@exemplo.com', 'A IA na medicina é uma revolução silenciosa. Ótimo artigo.', '2025-09-04 12:40:10', 1),
(105, 'Leonardo Alves', 'leo.alves@exemplo.com', 'Comecei minha rotina de exercícios em casa por causa deste post. Valeu!', '2025-09-04 13:10:25', 1);

/* Inserts autores
Informações fictícias geradas com IA */

INSERT INTO Autores (nome, email, bio) VALUES
('Ana Silva', 'ana.silva@email.com', 'Especialista em marketing digital e entusiasta de tecnologia.'),
('Bruno Costa', 'bruno.costa@email.com', 'Desenvolvedor Full-Stack com paixão por código limpo e boas práticas.'),
('Carla Dias', 'carla.dias@email.com', 'Designer UX/UI focada em criar experiências de usuário intuitivas e agradáveis.'),
('Daniel Martins', 'daniel.martins@email.com', 'Fotógrafo de viagens e contador de histórias visuais.'),
('Eduarda Ferreira', 'eduarda.ferreira@email.com', 'Chef de cozinha e blogueira de culinária, explorando sabores do mundo.'),
('Fábio Pereira', 'fabio.pereira@email.com', 'Consultor financeiro, ajudando pessoas a organizar suas finanças pessoais.'),
('Gabriela Ramos', 'gabriela.ramos@email.com', 'Jornalista investigativa com foco em política e sociedade.'),
('Hugo Almeida', 'hugo.almeida@email.com', 'Músico, produtor e crítico musical.'),
('Isabela Gomes', 'isabela.gomes@email.com', 'Cientista de dados transformando números em insights poderosos.'),
('João Rodrigues', 'joao.rodrigues@email.com', 'Entusiasta de fitness e vida saudável, compartilhando dicas e treinos.'),
('Karen Souza', 'karen.souza@email.com', 'Arquiteta e urbanista, apaixonada por cidades inteligentes e sustentabilidade.'),
('Lucas Barbosa', 'lucas.barbosa@email.com', 'Especialista em cibersegurança e privacidade de dados.'),
('Mariana Lima', 'mariana.lima@email.com', 'Bióloga marinha e ativista ambiental.'),
('Nelson Vieira', 'nelson.vieira@email.com', 'Professor de história e amante de curiosidades sobre o passado.'),
('Olívia Castro', 'olivia.castro@email.com', 'Escritora de ficção científica e fantasia.'),
('Paulo Azevedo', 'paulo.azevedo@email.com', 'Engenheiro de software sênior, trabalhando com sistemas distribuídos.'),
('Quintino Barros', 'quintino.barros@email.com', 'Sommelier de vinhos e especialista em enogastronomia.'),
('Rita Moreira', 'rita.moreira@email.com', 'Psicóloga clínica, escrevendo sobre saúde mental e bem-estar.'),
('Sérgio Carvalho', 'sergio.carvalho@email.com', 'Empreendedor serial e mentor de startups.'),
('Tatiana Nogueira', 'tatiana.nogueira@email.com', 'Profissional de RH e especialista em desenvolvimento de carreira.'),
('Ulisses Mendes', 'ulisses.mendes@email.com', 'Aventureiro e guia de ecoturismo.'),
('Vanessa Santos', 'vanessa.santos@email.com', 'Crítica de cinema e séries, sempre de olho nos últimos lançamentos.'),
('William Tavares', 'william.tavares@email.com', 'Especialista em inteligência artificial e aprendizado de máquina.'),
('Xavier Pinto', 'xavier.pinto@email.com', 'Investidor do mercado de ações e analista financeiro.'),
('Yasmin Correia', 'yasmin.correia@email.com', 'Artista plástica e curadora de arte contemporânea.'),
('Zeca Lopes', 'zeca.lopes@email.com', 'Mecânico e entusiasta de carros clássicos.'),
('Amanda Faria', 'amanda.faria@email.com', 'Nutricionista esportiva e criadora de receitas saudáveis.'),
('Bernardo Neves', 'bernardo.neves@email.com', 'Desenvolvedor de jogos indie.'),
('Clara Pires', 'clara.pires@email.com', 'Tradutora e intérprete, fluente em cinco idiomas.'),
('Diogo Ribeiro', 'diogo.ribeiro@email.com', 'Físico e divulgador científico.'),
('Elisa Matos', 'elisa.matos@email.com', 'Veterinária e defensora dos direitos dos animais.'),
('Felipe Cunha', 'felipe.cunha@email.com', 'Piloto de avião e entusiasta da aviação.'),
('Giovana Brandão', 'giovana.brandao@email.com', 'Designer de moda sustentável.'),
('Heitor Bastos', 'heitor.bastos@email.com', 'Advogado especializado em direito digital.'),
('Igor Esteves', 'igor.esteves@email.com', 'Geógrafo e pesquisador de mudanças climáticas.'),
('Júlia Drummond', 'julia.drummond@email.com', 'Personal organizer, ajudando a simplificar a vida das pessoas.'),
('Kevin Arruda', 'kevin.arruda@email.com', 'DJ e produtor de música eletrônica.'),
('Laura Melo', 'laura.melo@email.com', 'Pedagoga e especialista em educação infantil.'),
('Miguel Teixeira', 'miguel.teixeira@email.com', 'Historiador da arte, focado no período renascentista.'),
('Natália Valente', 'natalia.valente@email.com', 'Influenciadora digital de lifestyle e bem-estar.'),
('Otávio Rezende', 'otavio.rezende@email.com', 'Engenheiro agrônomo e especialista em agricultura orgânica.'),
('Priscila Fontes', 'priscila.fontes@email.com', 'Coach de vida e carreira.'),
('Rafael Dantas', 'rafael.dantas@email.com', 'Cineasta e diretor de documentários.'),
('Sofia Xavier', 'sofia.xavier@email.com', 'Astrônoma amadora e observadora de estrelas.'),
('Thiago Guerra', 'thiago.guerra@email.com', 'Analista de sistemas e especialista em otimização de performance.'),
('Úrsula Pimenta', 'ursula.pimenta@email.com', 'Chef confeiteira e dona de uma doceria famosa.'),
('Vitor Novais', 'vitor.novais@email.com', 'Especialista em marketing de conteúdo e SEO.'),
('Wendy Andrade', 'wendy.andrade@email.com', 'Ilustradora e criadora de histórias em quadrinhos.'),
('Yuri Bernardes', 'yuri.bernardes@email.com', 'Atleta profissional de skate.');

/* Inserts categorias
Informações fictícias geradas com IA */

INSERT INTO Categorias (nome) VALUES
('Tecnologia'), ('Desenvolvimento Web'), ('Culinária'), ('Viagens'), ('Finanças Pessoais'),
('Marketing Digital'), ('Fotografia'), ('Saúde e Bem-estar'), ('Produtividade'), ('Carreira'),
('Música'), ('Cinema e Séries'), ('Literatura'), ('Ciência'), ('Educação'),
('Sustentabilidade'), ('Design'), ('Arquitetura'), ('Moda'), ('Esportes'),
('História'), ('Política'), ('Psicologia'), ('Empreendedorismo'), ('Startups'),
('Inteligência Artificial'), ('Cibersegurança'), ('Natureza'), ('Animais'), ('Decoração'),
('Família'), ('Relacionamentos'), ('Notícias'), ('Inovação'), ('Gadgets'),
('Receitas'), ('Destinos Turísticos'), ('Investimentos'), ('SEO'), ('UX/UI Design'),
('Games'), ('Cultura Pop'), ('Arte'), ('Astronomia'), ('Biologia'),
('Carros'), ('Receitas Veganas'), ('Minimalismo'), ('Trabalho Remoto'), ('Idiomas');